spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev

server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driverClassName: oracle.jdbc.driver.OracleDriver              # oracle驱动包
    url: jdbc:oracle:thin:@localhost:1521/ORCL              # 数据库名称
    username: scott
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j,config
    connectionProperties: password=xxxxx_tiger
    passwordCallbackClassName: com.springcloud.config.DbPasswordCallback

eureka:
   client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
   instance:
    instance-id: microservicecloud-dept8001  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

---
spring:
  profiles: test
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driverClassName: oracle.jdbc.driver.OracleDriver              # oracle驱动包
    url: jdbc:oracle:thin:@localhost:1521/ORCL              # 数据库名称
    username: scott
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j,config
    connectionProperties: password=xxxxx_tiger
    passwordCallbackClassName: com.springcloud.config.DbPasswordCallback

eureka:
   client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
   instance:
    instance-id: microservicecloud-dept8001  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
